### ISSUE TITLE
Subscriptions example

### ISSUE THREAD

**Issue by kabriel** [aws-samples/aws-mobile-appsync-events-starter-react-native#2]
The README states that this example shows: "GraphQL Subscriptions - Real time updates for comments on an event". That doesn't seem to be the case yet, which is understandable as this is in preview! Just adding an issue here to track progress so we can be notified when it is available.

**Comment by dk0r** [comment]
..waiting on this

**Comment by dabit3** [comment]
Yo @dk0r @kabriel we have a pr for this, should be updated soon.

**Comment by manueliglesias** [comment]
Closed by #6 
Thanks @dabit3 !
